apiVersion: networking.k8s.io/v1 # to test - curl http://34.123.45.67/prometheus for example
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules: # removed:   - host: "*"   # Allows access via public IP or domain
  - http:
      paths:
      - path: /flask
        pathType: Prefix
        backend:
          service:
            name: flask-app-service
            port:
              number: 80
      - path: /argo
        pathType: Prefix
        backend:
          service:
            name: argocd-server-external
            port:
              number: 80
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus-server-external
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-server-external
            port:
              number: 80
