apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-external
  namespace: default
spec:
  type: ExternalName
  externalName: monitor-stack-prometheus-server.monitor.svc.cluster.local
  ports:
    - port: 80
