# service monitor and dashboards are outside of this file, sidecar used.
kube-prometheus-stack:
  grafana:
    adminPassword: "admin"
    grafana.ini:
      date_format:
        default_timezone: "browser"
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: loki-auto
            type: loki
            uid: loki-omri
            url: http://loki.log.svc.cluster.local:3100
            access: proxy
            isDefault: false
            jsonData:
              maxLines: 1000

  prometheus:
    prometheusSpec:
      serviceMonitorSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: false
