version: "3.8"

services:
  flask-app:
    build: . # build from the current directory, dockerfile.
    container_name: flask
    image: crazyguy888/flask-compose-catproject:${TAG:-latest} # to which image docker compose directing to install.
    ports:
      - "${PORT}:${PORT}" # using the PORT variable from the .env file.
    environment:
      - FLASK_ENV=${FLASK_ENV}         # Fetch from .env file
      - MYSQL_HOST=${MYSQL_HOST}       # Fetch from .env file
      - MYSQL_USER=${MYSQL_USER}       # Fetch from .env file
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} # Fetch from .env file
      - MYSQL_DATABASE=${MYSQL_DATABASE} # Fetch from .env file.
      - PORT=${PORT}                   # Fetch from .env file, pass the PORT variable to the container.
    depends_on:
      - db
    networks:
      - flask-network

  db:
    image: mysql:5.7  # Downgrade to MySQL 5.7
    container_name: mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}          # Fetch from .env file
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  # Fetch from .env file
      - MYSQL_DATABASE=${MYSQL_DATABASE}  # Fetch from .env file
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Fetch from .env file
    ports:
      - "3308:3306"  # Host's port 3308 maps to container's port 3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Mount the init.sql file
    networks:
      - flask-network

networks:
  flask-network:

volumes:
  db_data: