apiVersion: v2
name: monitor-stack
description: An Umbrella chart for kube-prometheus-stack and custom additional resources.
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "48.2.2" # use the latest available each time.
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: custom-resources
    version: "0.1.0"
    repository: "file://charts/custom-resources"
