prometheus-operator:
  enabled: true
  prometheus:
    enabled: true
    service:
      type: ClusterIP
    prometheusSpec:
      serviceMonitorNamespaceSelector:
        matchNames:
          - monitor
      serviceMonitorSelector: {}
  alertmanager:
    enabled: false  # Disable Alertmanager
  grafana:
    enabled: false  # Disable Grafana
  kubeControllerManager:
    enabled: false  # Disable Kubernetes Controller Manager monitoring
  kubeScheduler:
    enabled: false  # Disable Kubernetes Scheduler monitoring
  kubeEtcd:
    enabled: false  # Disable etcd monitoring
  kubeStateMetrics:
    enabled: false  # Disable Kube State Metrics
  nodeExporter:
    enabled: false  # Disable Node Exporter
  coreDns:
    enabled: false  # Disable CoreDNS monitoring
  kubeApiServer:
    enabled: false  # Disable Kubernetes API server monitoring
  kubelet:
    enabled: false  # Disable Kubelet monitoring

grafana:
  grafana.ini:
    date_format:
      default_timezone: "browser"
  service:
    type: ClusterIP
  persistence:
    enabled: false  # Disable PV for simplicity
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitor.svc.cluster.local  # Update if needed
          access: proxy
          isDefault: true
        - name: loki-auto
          type: loki
          uid: loki-omri
          url: http://loki.log.svc.cluster.local:3100
          access: proxy
          isDefault: false
          jsonData:
            maxLines: 1000
  sidecar:
    dashboards:
      enabled: true        # Enable the sidecar that automatically imports dashboards
      label: grafana_dashboard  # Specify the label that the sidecar will use to pick up dashboards
      label_value: "1"     