apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Ensures CRDs deploy first
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # Directly reference the Helm repo
    targetRevision: 48.2.2  # Match your kube-prometheus-stack version
    chart: kube-prometheus-stack
    helm:
      values: |  # Disable all components except CRDs
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    syncOptions:
      - ServerSideApply=true  # Critical for large CRDs
      - CreateNamespace=true
    automated: null