apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki  
  namespace: argocd  # Namespace where ArgoCD is running
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # ArgoCD project to which this app belongs
  source:
    repoURL: https://github.com/OmriFialkov/ArgoCD-Charts 
    targetRevision: main 
    path: log  
  destination:
    server: https://kubernetes.default.svc 
    namespace: log  # Target namespace for the Loki app
  syncPolicy:
    automated: # Set to 'null' for manual sync
      selfHeal: true
      prune: true