apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OmriFialkov/ArgoCD-Charts
    targetRevision: main
    path: monitor-stack-argo  # Path to the umbrella chart
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor  # Ensure Prometheus and Grafana are in the same namespace
  syncPolicy:
    automated:
      prune: true # prune true in ui must be true - manually check.
      selfHeal: true