apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after CRDs
spec:
  project: default
  source:
    repoURL: https://github.com/OmriFialkov/flask-catexer-app-actions
    targetRevision: main
    path: argocd/monitor-stack
    helm:
      values: |  # Skip CRD installation
        kube-prometheus-stack:
          skipCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitor
  syncPolicy:
    syncOptions:
      - PruneLast=true
    automated: null