apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: crazyguy888/catexer-actions:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        env:
        # VARIABLES FROM K8S CONFIG MAP
        - name: FLASK_ENV
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: FLASK_ENV
        - name: MYSQL_HOST # MySQL service yaml name
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_DATABASE
        - name: PORT
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
