apiVersion: v2
name: helm-flask
description: A k8s Helm chart for Flask application
type: application
version: 0.1.0 # wil be edited dynamically
appVersion: "1.16.0"
# this file was modified by a ci to update helm version tagging
