name: cleanups

on:
  workflow_dispatch:

env:
    DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
    HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: cleaning up docker hub older tags
        run: |
          chmod +x ./cleanups/docker-clean.sh
          ./cleanups/docker-clean.sh

      - name: Cleaning Up Old Helm Charts in Helm Repo 
        run: |
          cd cleanups
          ls -lrta
          chmod +x ./helm-clean.sh
          ./helm-clean.sh