name: cleanups

on:
  workflow_dispatch: # should add automatically in the future...

env:
    DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}
    DOCKER_USER: ${{ secrets.DOCKER_USER }}
    DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
    HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # bash <script> or chmod +x <script> then ./<script>

      - name: cleaning up docker hub older tags
        run: |
          bash ./cleanups/docker-clean.sh

      - name: Cleaning Up Old Helm Charts in Helm Repo 
        run: |
          bash ./cleanups/helm-clean.sh