name: helm ci

on:
    push:
      paths:
        - 'charts/helm-flask/**'
      branches:
        - main
    pull_request:
      paths:
        - 'charts/helm-flask/**'
      branches:
        - main
    workflow_run:
      workflows: ["app ci"]
      types:
        - completed

jobs:
  helm-chart-update:
        runs-on: ubuntu-latest
        if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: verify app ci is not running simultaneously to prevent conflicts # a situation where theres a change in both charts and app.
              run: |
                set -x
                sleep 5
                RUNNING=$(curl -s -H "Authorization: token ${{ secrets.HELM_REPO_PAT }}" \
                 "https://api.github.com/repos/OmriFialkov/flask-catexer-app-actions/actions/runs?status=in_progress" \
                 | jq 'if .workflow_runs then [ .workflow_runs[] | select(.name == "app ci") ] | length else 0 end')

                if [ "$RUNNING" -gt 0 ]; then
                  echo "app ci is running"
                  exit 1
                else
                  echo "app ci is not running, continuing.."
                fi

            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Helm
              run: |
                curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
                helm version

            - name: Update Helm Chart Version
              run: |
                cd charts/helm-flask
                sed -i "s/version: .*/version: 0.0.${{ github.run_number }}/g" ./Chart.yaml
                echo "# this file was modified by a ci to update helm version tagging" >> ./Chart.yaml

            - name: Debug Triggering Workflow
              run: |
               echo "Triggered by workflow: '${{ toJSON(github.event.workflow_run.name) }}'"

            - name: Download Image Tag Artifact from App CI - Only If Triggered By App CI
              if: ${{ github.event.workflow_run.name == 'app ci' }}
              uses: actions/download-artifact@v4
              with:
                name: image_tag
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ secrets.HELM_REPO_PAT }}
              

            - name: Update Image Tag in values.yaml - Only If Triggered By App CI
              if: ${{ github.event.workflow_run.name == 'app ci' }}
              run: |
                set -x
                ls -lrta
                IMAGE_TAG=$(cat image_tag.txt)
                echo "updating image tag in values.yaml to ${IMAGE_TAG}"
                cd charts/helm-flask
                sed -i "s/tag: .*/tag: ${IMAGE_TAG}/g" ./values.yaml
                cat ./values.yaml

            - name: Package Helm Chart
              run: |
                cd charts
                helm package helm-flask --destination ..
                cd ..
                ls -lrta

            - name: Update Helm Repo Index # searches for tar.gz file in same dir.
              run: |
                helm repo index --url https://omrifialkov.github.io/helm-flaskgif .
                ls -lrta

            - name: Push helm chart ( tgz and index.yaml ) to helm repo
              env:
                HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }} 
              run: |
                set -x
                git clone https://${HELM_REPO_PAT}@github.com/OmriFialkov/helm-flaskgif.git helmrepo
                cd helmrepo
                pwd

                git config --global user.name "github-actions-app"
                git config --global user.email "github-actions@gmail.com"
                ls -lrta

                rm -f *.tgz && rm -f index.yaml
                cp ../*.tgz .
                cp ../index.yaml .
                ls -lrta

                git add .
                git commit -m "Updated helm chart version from APP REPO TRIGGER - Version 0.0.${{ github.run_number }}"
                git push origin main

                echo "pushed updated helm chart to helm-repo"


            